version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bidding-system
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/usr/src/app

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
