name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'       # Trigger only if files in the backend folder change
  pull_request:
    paths:
      - 'backend/**' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the backend
    - name: Build backend Docker image
      run: |
        docker build -t bidding-backend ./backend

    # Step 3: Deploy backend to Render
    - name: Deploy backend to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true