name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the backend
    - name: Build backend Docker image
      run: |
        docker build -t bidding-backend ./backend

    # Step 3: Build frontend image
    - name: Build frontend Docker image
      run: |
        docker build -t bidding-frontend ./frontend

    # Step 4: Deploy frontend to Vercel
    - name: Deploy frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

    # Step 5: Deploy backend to Render
    - name: Deploy backend to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true