name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'       # Trigger only if files in the frontend folder change
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build frontend image
    - name: Build frontend Docker image
      run: |
        docker build -t bidding-frontend ./frontend

    # Step 3: Deploy frontend to Vercel
    - name: Deploy frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
